export const FETCHING_DRINKS = 'FETCHING_DRINKS';
export const FETCHING_DRINKS_SUCCESS = 'FETCHING_DRINKS_SUCCESS';
export const FETCHING_DRINKS_ERROR = 'FETCHING_DRINKS_ERROR';
export const CLEAN_DRINKS = 'CLEAN_DRINKS';
